// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/rizkyzhang/ayobeli-backend-golang/domain"
)

type UserUsecaseMock struct {
	GetAdminByUserIDStub        func(int) (*domain.AdminModel, error)
	getAdminByUserIDMutex       sync.RWMutex
	getAdminByUserIDArgsForCall []struct {
		arg1 int
	}
	getAdminByUserIDReturns struct {
		result1 *domain.AdminModel
		result2 error
	}
	getAdminByUserIDReturnsOnCall map[int]struct {
		result1 *domain.AdminModel
		result2 error
	}
	GetUserByFirebaseUIDStub        func(string) (*domain.UserModel, error)
	getUserByFirebaseUIDMutex       sync.RWMutex
	getUserByFirebaseUIDArgsForCall []struct {
		arg1 string
	}
	getUserByFirebaseUIDReturns struct {
		result1 *domain.UserModel
		result2 error
	}
	getUserByFirebaseUIDReturnsOnCall map[int]struct {
		result1 *domain.UserModel
		result2 error
	}
	GetUserByUIDStub        func(string) (*domain.UserModel, error)
	getUserByUIDMutex       sync.RWMutex
	getUserByUIDArgsForCall []struct {
		arg1 string
	}
	getUserByUIDReturns struct {
		result1 *domain.UserModel
		result2 error
	}
	getUserByUIDReturnsOnCall map[int]struct {
		result1 *domain.UserModel
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *UserUsecaseMock) GetAdminByUserID(arg1 int) (*domain.AdminModel, error) {
	fake.getAdminByUserIDMutex.Lock()
	ret, specificReturn := fake.getAdminByUserIDReturnsOnCall[len(fake.getAdminByUserIDArgsForCall)]
	fake.getAdminByUserIDArgsForCall = append(fake.getAdminByUserIDArgsForCall, struct {
		arg1 int
	}{arg1})
	stub := fake.GetAdminByUserIDStub
	fakeReturns := fake.getAdminByUserIDReturns
	fake.recordInvocation("GetAdminByUserID", []interface{}{arg1})
	fake.getAdminByUserIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *UserUsecaseMock) GetAdminByUserIDCallCount() int {
	fake.getAdminByUserIDMutex.RLock()
	defer fake.getAdminByUserIDMutex.RUnlock()
	return len(fake.getAdminByUserIDArgsForCall)
}

func (fake *UserUsecaseMock) GetAdminByUserIDCalls(stub func(int) (*domain.AdminModel, error)) {
	fake.getAdminByUserIDMutex.Lock()
	defer fake.getAdminByUserIDMutex.Unlock()
	fake.GetAdminByUserIDStub = stub
}

func (fake *UserUsecaseMock) GetAdminByUserIDArgsForCall(i int) int {
	fake.getAdminByUserIDMutex.RLock()
	defer fake.getAdminByUserIDMutex.RUnlock()
	argsForCall := fake.getAdminByUserIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *UserUsecaseMock) GetAdminByUserIDReturns(result1 *domain.AdminModel, result2 error) {
	fake.getAdminByUserIDMutex.Lock()
	defer fake.getAdminByUserIDMutex.Unlock()
	fake.GetAdminByUserIDStub = nil
	fake.getAdminByUserIDReturns = struct {
		result1 *domain.AdminModel
		result2 error
	}{result1, result2}
}

func (fake *UserUsecaseMock) GetAdminByUserIDReturnsOnCall(i int, result1 *domain.AdminModel, result2 error) {
	fake.getAdminByUserIDMutex.Lock()
	defer fake.getAdminByUserIDMutex.Unlock()
	fake.GetAdminByUserIDStub = nil
	if fake.getAdminByUserIDReturnsOnCall == nil {
		fake.getAdminByUserIDReturnsOnCall = make(map[int]struct {
			result1 *domain.AdminModel
			result2 error
		})
	}
	fake.getAdminByUserIDReturnsOnCall[i] = struct {
		result1 *domain.AdminModel
		result2 error
	}{result1, result2}
}

func (fake *UserUsecaseMock) GetUserByFirebaseUID(arg1 string) (*domain.UserModel, error) {
	fake.getUserByFirebaseUIDMutex.Lock()
	ret, specificReturn := fake.getUserByFirebaseUIDReturnsOnCall[len(fake.getUserByFirebaseUIDArgsForCall)]
	fake.getUserByFirebaseUIDArgsForCall = append(fake.getUserByFirebaseUIDArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetUserByFirebaseUIDStub
	fakeReturns := fake.getUserByFirebaseUIDReturns
	fake.recordInvocation("GetUserByFirebaseUID", []interface{}{arg1})
	fake.getUserByFirebaseUIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *UserUsecaseMock) GetUserByFirebaseUIDCallCount() int {
	fake.getUserByFirebaseUIDMutex.RLock()
	defer fake.getUserByFirebaseUIDMutex.RUnlock()
	return len(fake.getUserByFirebaseUIDArgsForCall)
}

func (fake *UserUsecaseMock) GetUserByFirebaseUIDCalls(stub func(string) (*domain.UserModel, error)) {
	fake.getUserByFirebaseUIDMutex.Lock()
	defer fake.getUserByFirebaseUIDMutex.Unlock()
	fake.GetUserByFirebaseUIDStub = stub
}

func (fake *UserUsecaseMock) GetUserByFirebaseUIDArgsForCall(i int) string {
	fake.getUserByFirebaseUIDMutex.RLock()
	defer fake.getUserByFirebaseUIDMutex.RUnlock()
	argsForCall := fake.getUserByFirebaseUIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *UserUsecaseMock) GetUserByFirebaseUIDReturns(result1 *domain.UserModel, result2 error) {
	fake.getUserByFirebaseUIDMutex.Lock()
	defer fake.getUserByFirebaseUIDMutex.Unlock()
	fake.GetUserByFirebaseUIDStub = nil
	fake.getUserByFirebaseUIDReturns = struct {
		result1 *domain.UserModel
		result2 error
	}{result1, result2}
}

func (fake *UserUsecaseMock) GetUserByFirebaseUIDReturnsOnCall(i int, result1 *domain.UserModel, result2 error) {
	fake.getUserByFirebaseUIDMutex.Lock()
	defer fake.getUserByFirebaseUIDMutex.Unlock()
	fake.GetUserByFirebaseUIDStub = nil
	if fake.getUserByFirebaseUIDReturnsOnCall == nil {
		fake.getUserByFirebaseUIDReturnsOnCall = make(map[int]struct {
			result1 *domain.UserModel
			result2 error
		})
	}
	fake.getUserByFirebaseUIDReturnsOnCall[i] = struct {
		result1 *domain.UserModel
		result2 error
	}{result1, result2}
}

func (fake *UserUsecaseMock) GetUserByUID(arg1 string) (*domain.UserModel, error) {
	fake.getUserByUIDMutex.Lock()
	ret, specificReturn := fake.getUserByUIDReturnsOnCall[len(fake.getUserByUIDArgsForCall)]
	fake.getUserByUIDArgsForCall = append(fake.getUserByUIDArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetUserByUIDStub
	fakeReturns := fake.getUserByUIDReturns
	fake.recordInvocation("GetUserByUID", []interface{}{arg1})
	fake.getUserByUIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *UserUsecaseMock) GetUserByUIDCallCount() int {
	fake.getUserByUIDMutex.RLock()
	defer fake.getUserByUIDMutex.RUnlock()
	return len(fake.getUserByUIDArgsForCall)
}

func (fake *UserUsecaseMock) GetUserByUIDCalls(stub func(string) (*domain.UserModel, error)) {
	fake.getUserByUIDMutex.Lock()
	defer fake.getUserByUIDMutex.Unlock()
	fake.GetUserByUIDStub = stub
}

func (fake *UserUsecaseMock) GetUserByUIDArgsForCall(i int) string {
	fake.getUserByUIDMutex.RLock()
	defer fake.getUserByUIDMutex.RUnlock()
	argsForCall := fake.getUserByUIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *UserUsecaseMock) GetUserByUIDReturns(result1 *domain.UserModel, result2 error) {
	fake.getUserByUIDMutex.Lock()
	defer fake.getUserByUIDMutex.Unlock()
	fake.GetUserByUIDStub = nil
	fake.getUserByUIDReturns = struct {
		result1 *domain.UserModel
		result2 error
	}{result1, result2}
}

func (fake *UserUsecaseMock) GetUserByUIDReturnsOnCall(i int, result1 *domain.UserModel, result2 error) {
	fake.getUserByUIDMutex.Lock()
	defer fake.getUserByUIDMutex.Unlock()
	fake.GetUserByUIDStub = nil
	if fake.getUserByUIDReturnsOnCall == nil {
		fake.getUserByUIDReturnsOnCall = make(map[int]struct {
			result1 *domain.UserModel
			result2 error
		})
	}
	fake.getUserByUIDReturnsOnCall[i] = struct {
		result1 *domain.UserModel
		result2 error
	}{result1, result2}
}

func (fake *UserUsecaseMock) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAdminByUserIDMutex.RLock()
	defer fake.getAdminByUserIDMutex.RUnlock()
	fake.getUserByFirebaseUIDMutex.RLock()
	defer fake.getUserByFirebaseUIDMutex.RUnlock()
	fake.getUserByUIDMutex.RLock()
	defer fake.getUserByUIDMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *UserUsecaseMock) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ domain.UserUsecase = new(UserUsecaseMock)
