CREATE TABLE admins (
  id BIGSERIAL PRIMARY KEY,
  uid TEXT NOT NULL,
  email TEXT NOT NULL,
  user_id BIGINT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL,

  FOREIGN KEY(user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
);