basePath: /api/v1
definitions:
  domain.AuthControllerPayloadGetAccessToken:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  domain.AuthControllerPayloadSignUp:
    properties:
      email:
        type: string
      is_admin:
        type: boolean
      password:
        minLength: 8
        type: string
    required:
    - email
    - is_admin
    - password
    type: object
info:
  contact: {}
  description: Yet another e-commerce API
  license:
    name: MIT
    url: https://opensource.org/license/MIT
  title: Ayobeli API
  version: "0.1"
paths:
  /auth/access-token:
    post:
      consumes:
      - application/json
      parameters:
      - description: email and password
        in: body
        name: credential
        required: true
        schema:
          $ref: '#/definitions/domain.AuthControllerPayloadGetAccessToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: validation error
        "404":
          description: user not found
        "500":
          description: Internal Server Error
      summary: Get access token
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: email and password
        in: body
        name: credential
        required: true
        schema:
          $ref: '#/definitions/domain.AuthControllerPayloadSignUp'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: validation error | user already exist
        "500":
          description: Internal Server Error
      summary: Create user
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    description: Firebase auth access token, get it from POST /auth/access-token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
